In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import preprocessing, neighbors
df = pd.read_csv('breast-cancer-wisconsin.data')
df.replace('?', -99999, inplace=True)
df.drop(['Id'],axis=1,inplace=True)

In [2]:
print(df)

     Clump_thickness  Unif_cell_size  Unif_cell_shape  marg_adhesion  \
0                  5               1                1              1
1                  5               4                4              5
2                  3               1                1              1
3                  6               8                8              1
4                  4               1                1              3
5                  8              10               10              8
6                  1               1                1              1
7                  2               1                2              1
8                  2               1                1              1
9                  4               2                1              1
10                 1               1                1              1
11                 2               1                1              1
12                 5               3                3              3
13                 1               1                1              1
14                 8               7                5             10
15                 7               4                6              4
16                 4               1                1              1
17                 4               1                1              1
18                10               7                7              6
19                 6               1                1              1
20                 7               3                2             10
21                10               5                5              3
22                 3               1                1              1
23                 8               4                5              1
24                 1               1                1              1
25                 5               2                3              4
26                 3               2                1              1
27                 5               1                1              1
28                 2               1                1              1
29                 1               1                3              1
..               ...             ...              ...            ...
669                5              10               10              8
670                3              10                7              8
671                3               2                1              2
672                2               1                1              1
673                5               3                2              1
674                1               1                1              1
675                4               1                4              1
676                1               1                2              1
677                5               1                1              1
678                1               1                1              1
679                2               1                1              1
680               10              10               10             10
681                5              10               10             10
682                5               1                1              1
683                1               1                1              1
684                1               1                1              1
685                1               1                1              1
686                1               1                1              1
687                3               1                1              1
688                4               1                1              1
689                1               1                1              1
690                1               1                1              3
691                5              10               10              5
692                3               1                1              1
693                3               1                1              1
694                3               1                1              1
695                2               1                1              1
696                5              10               10              3
697                4               8                6              4
698                4               8                8              5

     Single_epith_cell_size Bare_nuclie  Bland_chrom  Norm_nucleoli  Mitosis  \
0                         2           1            3              1        1
1                         7          10            3              2        1
2                         2           2            3              1        1
3                         3           4            3              7        1
4                         2           1            3              1        1
5                         7          10            9              7        1
6                         2          10            3              1        1
7                         2           1            3              1        1
8                         2           1            1              1        5
9                         2           1            2              1        1
10                        1           1            3              1        1
11                        2           1            2              1        1
12                        2           3            4              4        1
13                        2           3            3              1        1
14                        7           9            5              5        4
15                        6           1            4              3        1
16                        2           1            2              1        1
17                        2           1            3              1        1
18                        4          10            4              1        2
19                        2           1            3              1        1
20                        5          10            5              4        4
21                        6           7            7             10        1
22                        2           1            2              1        1
23                        2      -99999            7              3        1
24                        2           1            3              1        1
25                        2           7            3              6        1
26                        1           1            2              1        1
27                        2           1            2              1        1
28                        2           1            2              1        1
29                        2           1            1              1        1
..                      ...         ...          ...            ...      ...
669                       5           5            7             10        1
670                       5           8            7              4        1
671                       2           1            3              1        1
672                       2           1            3              1        1
673                       3           1            1              1        1
674                       2           1            2              1        1
675                       2           1            1              1        1
676                       2           1            2              1        1
677                       2           1            1              1        1
678                       2           1            1              1        1
679                       2           1            1              1        1
680                       5          10           10             10        7
681                       4          10            5              6        3
682                       2           1            3              2        1
683                       2           1            1              1        1
684                       2           1            1              1        1
685                       2           1            1              1        1
686                       2           1            1              1        1
687                       2           1            2              3        1
688                       2           1            1              1        1
689                       2           1            1              1        8
690                       2           1            1              1        1
691                       4           5            4              4        1
692                       2           1            1              1        1
693                       2           1            2              1        2
694                       3           2            1              1        1
695                       2           1            1              1        1
696                       7           3            8             10        2
697                       3           4           10              6        1
698                       4           5           10              4        1

     Class
0        2
1        2
2        2
3        2
4        2
5        4
6        2
7        2
8        2
9        2
10       2
11       2
12       4
13       2
14       4
15       4
16       2
17       2
18       4
19       2
20       4
21       4
22       2
23       4
24       2
25       4
26       2
27       2
28       2
29       2
..     ...
669      4
670      4
671      2
672      2
673      2
674      2
675      2
676      2
677      2
678      2
679      2
680      4
681      4
682      2
683      2
684      2
685      2
686      2
687      2
688      2
689      2
690      2
691      4
692      2
693      2
694      2
695      2
696      4
697      4
698      4

[699 rows x 10 columns]

In [3]:
X = np.array(df.drop(['Class'],1))
y = np.array(df['Class'])

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [5]:
classifier = neighbors.KNeighborsClassifier()
classifier.fit(X_train, y_train)
accuracy = classifier.score(X_test, y_test)
print(accuracy)

0.9571428571428572

In [12]:
example_measures = np.array([[4,2,1,1,1,2,3,2,1],[4,2,1,2,2,2,3,2,1]])
example_measures = example_measures.reshape(len(example_measures), -1)
prediction = classifier.predict(example_measures)
print(prediction)

[2 2]